### ISSUE TITLE
Need the pre-processed dataset version of imagechd

### ISSUE THREAD

**Issue by Jonydom** [fkong7/SDF4CHD#1]
What a great job! Can you upload the preprocessed dataset as soon as possible?

**Comment by fkong7** [comment]
Thanks! I've added the segmentation and included a preprocessing script. Please see the updated readme for instructions.

**Comment by Jonydom** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
